### ISSUE TITLE
Multiselect Component setter does not add the selected pills.

### ISSUE THREAD

**Issue by imranhsayed** [Travelopia/web-components#17]
* When you use the [setter](https://github.com/Travelopia/web-components/blob/master/src/multi-select/tp-multi-select.ts#L84) of the tp-multi-select, it adds the selected attribute to the option, but does not add the pill.
* e.g. when we use `document.querySelector( 'tp-multi-select' ).value = ['24']`
<img width="818" alt="image" src="https://github.com/Travelopia/web-components/assets/11497423/99a66d43-11c0-479f-82c0-6201d86f4d1d">

Pills are not added.
<img width="330" alt="image" src="https://github.com/Travelopia/web-components/assets/11497423/417d9db8-578b-484b-a995-e03168052150">
<img width="513" alt="image" src="https://github.com/Travelopia/web-components/assets/11497423/2dc486c4-d91e-4261-8447-c95b5ebf389e">

Also the selected attribute value should be `yes` and not `selected`
selected="yes"
<img width="773" alt="image" src="https://github.com/Travelopia/web-components/assets/11497423/454eca77-ba42-4a2f-b543-892fa4a4774a">

**Comment by junaidbhura** [comment]
@i-am-chitti Do you think you could take a look at this one?

**Comment by junaidbhura** [comment]
@imranhsayed This is now fixed!

**Comment by imranhsayed** [comment]
Thanks @junaidbhura
