### ISSUE TITLE
Multi-select component not compatible with Modal Component

### ISSUE THREAD

**Issue by Souptik2001** [Travelopia/web-components#35]
In the `multi-select` component we are attaching a click event handler to the `tp-multi-select-field` component in the `connectedCallback` function -

https://github.com/Travelopia/web-components/blob/0282694079cc5d30cbc11c59ba4b3f9745e22907/src/multi-select/tp-multi-select-field.ts#L13-L15

But here is a edge case for that. Suppose we use this component inside a modal where we take the modal content and append it at the end of the body something like this -

```ts
this.body.appendChild( this );
```

In this case the `connectedCallback` of the `multi-select` component runs twice, and because of that the event listener gets attached twice to the element. And because of this the options dropdown never opens, because one of the event listener opens it and another closes it instantly.
Here I have given example of modal, but this is true with any wrapper which removes and attaches the component again and again.

![image](https://github.com/Travelopia/web-components/assets/39427067/cfc92ad8-4999-480f-827b-f1270e6de91d)

So, to solve this issue, I see two possibilities -

- Use `constructor` instead of `connectedCallback`, which will run only once -
```ts
constructor() {
  super();
  this.addEventListener("click", this.toggleOpen.bind(this));
}
```
- Or remove the event listener before adding it -
```ts
connectedCallback() {
	this.removeEventListener("click", this.toggleOpen.bind(this));
	this.addEventListener("click", this.toggleOpen.bind(this));
}
```

@junaidbhura @i-am-chitti Please let me know your thoughts on that. :pray:

**Comment by junaidbhura** [comment]
@Souptik2001 I like the second solution, so we are sure that event listeners are removed. But its weird that it wouldn't do this automatically!

Have you verified this approach?

**Comment by Souptik2001** [comment]
Thanks @junaidbhura !

One more approach which I wanted to suggest is something like this -

```js
connectedCallback() {
	if ( true === this.intialized ) {
		return;
	}

	this.addEventListener("click", this.toggleOpen.bind(this));

	this.intialized = true;
}
```

Do you think this will be cleaner?
I also tried with `disconnectedCallback` but seems like that callback is not running only the `connectedCallback` is running twice.

**Comment by junaidbhura** [comment]
Fixed in https://github.com/Travelopia/web-components/releases/tag/0.5.16
