### ISSUE TITLE
Add `transition-speed` attribute in Slider

### ISSUE THREAD

**Issue by vampdroid** [Travelopia/web-components#42]
Currently, the slider only uses the default `transition-duration` of 0.6s for changing the slide. We can provide an option of `transition-speed` that will change the `transition-duration` of our `tp-slider-slides` element.

We can add `transition-speed` attribute in observedAttributes array:
```ts
return [ 'current-slide', 'flexible-height', 'infinite', 'swipe', 'transition-speed' ];
```

And can check if this attribute is passed, and change slides container's transition-duration accordingly in TPSlider's `slide()` function.
```ts
		// First, update the height.
		this.updateHeight();

		// Update the transition-duration.
		const transitionSpeed: string = this.getAttribute( 'transition-speed' ) || '';
		if ( transitionSpeed ) {
			slidesContainer.style.transitionDuration = `${ transitionSpeed }ms`;
		}

		// Now lets slide!
		const behaviour: string = this.getAttribute( 'behaviour' ) || '';
		if ( 'fade' !== behaviour && slides[ this.currentSlideIndex - 1 ] ) {
			slidesContainer.style.left = `-${ slides[ this.currentSlideIndex - 1 ].offsetLeft }px`;
		}
```

**Comment by junaidbhura** [comment]
@vampdroid this is controlled via CSS - is there a reason we would need to do this via JS?
