### ISSUE TITLE
Add `slides-per-view` attribute to TPSlider

### ISSUE THREAD

**Issue by vampdroid** [Travelopia/web-components#43]
- When we have a slider with `infinite="yes"` and it has 5 slides in total, where we want to display 4 slides per view, we just adjust the CSS for child slides's flex property.
- Currently, when the user clicks on the arrow button(next), he/she has to click it for 5 times to get back to first slide. Slider adds up white space as slide element until then.
- To avoid this and create a mechanism where the Slider automatically redirects to the first slide just after swiping until the 5th (last) slide, we can create a attribute `slides-per-view`.

Approach:
- We will update the getTotalSlides() function to subtract the total number of slides based on the `slides-per-view` value:
```ts
		const slidesPerView: number = parseInt( this.getAttribute( 'slides-per-view' ) ?? '0' );

		const slides: NodeListOf<TPSliderSlideElement> | null | undefined = this.getSlideElements();

		if ( slides ) {
			return slidesPerView ? Math.floor( slides.length / slidesPerView ) + 1 : slides.length;
		}

		return 0;
```
- This way, for the above scenario, we will get 2 as the total slides count and the slider will redirect to first slide after 2 clicks on the next arrow button.
- With this approach, we will also have to adjust the height of the slider which currently just take current slide's index into account. We will instead take in account all the slides which are currently in the view like following:
```ts

		// Check if we have a flexible height.
		if ( 'yes' === this.getAttribute( 'flexible-height' ) ) {

			// Check if slides-per-view is set.
			if ( this.getAttribute( 'slides-per-view' ) || 0 > 1  ) {

				// Calculate max height slide in the current view.
				let slideHeights: Array<number> = [];
				const currentIndex: number = this.currentSlideIndex - 1;
				const slidesOnCurrentView: number = currentIndex + parseInt( this.getAttribute( 'slides-per-view' ) || '0' );

				// Traverse all slides in the current view and add their height to the array.
				for( let i = this.currentSlideIndex - 1; i < slidesOnCurrentView; i++ ) {
					slideHeights.push( slides[ i ].scrollHeight );
				}

				// Set the height of the container to be the max height of the slides in the current view.
				slidesContainer.style.height = `${ Math.max( ...slideHeights ) }px`;
				console.log(slidesContainer.style.height);
			}
			else {
				// Set the height of the container to be the height of the current slide.
				const height: number = slides[ this.currentSlideIndex - 1 ].scrollHeight;
				slidesContainer.style.height = `${ height }px`;
			}
		} else {
			// Set the height of the container to be the height of the tallest slide.
			let height: number = 0;
			slides.forEach( ( slide: TPSliderSlideElement ): void => {
				if ( slide.scrollHeight > height ) {
					height = slide.scrollHeight;
				}
			} );

			slidesContainer.style.height = `${ height }px`;
		}
```
The above code can be optimized for calculation.

This way we will just need to adjust the CSS of the component and pass `slides-per-view` to the slider and we will be able to avoid the white spaces slides.

**Comment by junaidbhura** [comment]
@vampdroid lets discuss this on our standup

**Comment by vampdroid** [comment]
Hi @junaidbhura,
I know we talked about this functionality in yesterday's standup, but I gave it one try and I think this functionality can actually reduce a lot of redundant code on the frontend.
I worked on this functionality and I am also explaining my approach where I also took into account of some edge cases, can you give it a look in the following videos? (the videos are of less than 7 minutes! its just loom has 5 min as a limit):
first - https://www.loom.com/share/ca6f5ea192d54354b07cac6c3ec96bdd
second - https://www.loom.com/share/18240d3155114bf7a7e29fd9a683b65c

**Comment by junaidbhura** [comment]
Thanks @vampdroid - there are still some things to consider like the counts and bullets. Can you please raise a PR for the `slides-per-view` and `step`?

Lets ignore the decimal values for now. Lets start here - and build on top of this

**Comment by junaidbhura** [comment]
Fixed in https://github.com/Travelopia/web-components/pull/54
