### ISSUE TITLE
Add an autoplay attribute to the `tp-slider`

### ISSUE THREAD

**Issue by benerd** [Travelopia/web-components#47]
@junaidbhura - There are scenarios where we don't have any arrows or nav pills to navigate between different slides. Now I am Working on `et-immersive-inquiry-form`  where each slide changes after every 4 seconds, so to implement this I had to wrap our `tp-slider` inside a custom component so that I can add add a `setInterval()` on it. 
FYR: [Markup](https://github.com/Travelopia/enchantingtravels/pull/661/files#diff-a94a110657c4026bf07797e766c178504c04614e14d3575b89fac6527312f1edR7), [JS](https://github.com/Travelopia/enchantingtravels/pull/661/files#diff-e7a0ecb23ef61b54cc5c021970952291eb9b6c9ac713fed0702318e6dc894a1eR63),  

I think it will be great if we can add the `autoplay` and `transition-speed` attribute, and then if the `autoplay="yes"` then we will do the below: 

`setInterval( () => {
    // Change the slide.
	    this.next();
}, this.getAttribute( 'transition-speed' ) );`

LMK your thoughts on this?

**Comment by junaidbhura** [comment]
Thanks @benerd would you like to pick this up?

**Comment by benerd** [comment]
sure @junaidbhura - I am picking it up.

**Comment by benerd** [comment]
@junaidbhura - here is the [PR](https://github.com/Travelopia/web-components/pull/49) for this, added an `auto-slide-interval` attribute as we for the setInterval to  change after a certain period of time.
