### ISSUE TITLE
TPSlider `overflow-x: clip` support

### ISSUE THREAD

**Issue by vampdroid** [Travelopia/web-components#64]
On iPhone 12 - iOS v. 14 and iPhone 13 v. 15, `overflow-x: clip` is not supported, causing the TPSlider to spread horizontally as below:

<img width="417" alt="Screenshot 2024-05-02 at 11 11 56 AM" src="https://github.com/Travelopia/web-components/assets/55312427/6a6f3a8e-f430-46b8-9ee3-d90852ba1350">

I have also tested the same issue on a real iPhone 12 device.

To resolve this issue, we need to keep a backup for the devices not supporting `overflow-x: clip` by adding `overflow-x: hidden` in the tp-slider-track

Below is a screenshot of this fixing the issue:
<img width="1209" alt="Screenshot 2024-05-02 at 11 20 41 AM" src="https://github.com/Travelopia/web-components/assets/55312427/166bd111-9660-4857-a3ff-58b656df3967">
<img width="1231" alt="Screenshot 2024-05-02 at 11 21 06 AM" src="https://github.com/Travelopia/web-components/assets/55312427/7ccbfb78-ebc4-4ce3-9436-5f7a04f0d004">

cc: @junaidbhura

**Comment by junaidbhura** [comment]
@vampdroid Thanks for creating the issue. You can override it on the site as needed!
