### ISSUE TITLE
Update Slider Component Height On Font Reload.

### ISSUE THREAD

**Issue by imranhsayed** [Travelopia/web-components#7]
**Problem**
* Because it takes time for the font to be loaded, the height gets calculated as per the default font. 
After the fonts are loaded the content size changes but the height is not update

**Solution**
* Update slide height on font load.
```javascript
const slider = document.querySelector( 'tp-slider' );
document.fonts.ready.then( () => slider.updateSliderHeight() );

**Comment by imranhsayed** [comment]
cc: @junaidbhura

**Comment by imranhsayed** [comment]
Thanks @junaidbhura 
I tried that. It does not work for font-changes.

**Comment by junaidbhura** [comment]
Thanks @imranhsayed !
