### ISSUE TITLE
Add a functionality for input number with increment and decrement buttons

### ISSUE THREAD

**Issue by sagarjadhav** [Travelopia/web-components#80]
<img width="547" alt="Screenshot 2024-10-04 at 4 15 06 PM" src="https://github.com/user-attachments/assets/cfae7028-1e1d-405d-8d58-2842e1a8c667">

**Comment by sagarjadhav** [comment]
@junaidbhura Added the PR - https://github.com/Travelopia/web-components/pull/81

**Comment by junaidbhura** [comment]
https://github.com/Travelopia/web-components/pull/81 is fixed
